### ISSUE TITLE
Add support for multi sessions

### ISSUE THREAD

**Issue by sc0ch** [IlyaSemenov/grammy-scenes#11]
Hello! grammy-scenes very useful and the only one plugin of its kind.
Please add multi session support function. Thanks.

**Comment by IlyaSemenov** [comment]
Would you come up with an imaginary example or use case?

**Comment by sc0ch** [comment]
grammy-scenes stop working, when sessions use "multi" mode. probably because ctx.session arg is hard-coded and scene parsing stops after first element. disabling multi use returns to work "as-usual".

grammy @ 1.15.2

**Comment by IlyaSemenov** [comment]
Ah, I see, you mean https://grammy.dev/plugins/session.html#multi-sessions

This library was developed when there was no such thing. As such, it is not supported at the moment. Thank you for report, this should be an easy addition I suppose.

**Comment by IlyaSemenov** [comment]
This was fixed in 7.3.1.
