### ISSUE TITLE
.wait() not work

### ISSUE THREAD

**Issue by Skull-coder** [IlyaSemenov/grammy-scenes#12]
![image](https://user-images.githubusercontent.com/81759686/235264538-ec822497-390a-47c1-b4d6-4c8902ff3f11.png)
![image](https://user-images.githubusercontent.com/81759686/235264552-5955a28b-58b3-4beb-988b-722c9c674dfc.png)
![image](https://user-images.githubusercontent.com/81759686/235264561-9a3ddf3b-56d2-43b8-adae-b81c80cdf8b5.png)

**Comment by IlyaSemenov** [comment]
I added this test to https://github.com/IlyaSemenov/grammy-scenes/blob/a3b637e8ea36b37ccb8c6594cd2fb4cfda72cfce/tests/readme-example.test.ts and it works:

```
❯ yarn dev tests/readme-example.test.ts
yarn run v1.22.19
$ NODE_OPTIONS='-r dotenv/config' nodemon --exec esr tests/readme-example.test.ts
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `esr tests/readme-example.test.ts`
Bot @xxx_test_robot started.
Entering main scene...
Saving session: {"scenes":{"stack":[{"scene":"main","pos":3}]}}
Saving session: {"scenes":{"stack":[{"scene":"main","pos":3}]}}
Saving session: {}
```

<img width="461" alt="image" src="https://user-images.githubusercontent.com/128121/235285420-390d464c-bb0b-4d13-a55d-dba5445b22d3.png">

Do you use perhaps use multi sessions? They are not supported at the moment - see #11, I'll try to fix this shortly.

**Comment by IlyaSemenov** [comment]
multi sessions are now supported. Please provide the full reproduction code if you still have errors.

**Comment by Skull-coder** [comment]
> multi sessions are now supported. Please provide the full reproduction code if you still have errors.

![image](https://user-images.githubusercontent.com/81759686/235296363-5c415ec6-b232-4bb3-98e4-f1e0cd3d3cdb.png)

**Comment by Skull-coder** [comment]
> > multi sessions are now supported. Please provide the full reproduction code if you still have errors.
> 
> ![image](https://user-images.githubusercontent.com/81759686/235296363-5c415ec6-b232-4bb3-98e4-f1e0cd3d3cdb.png)

Sorry, I forgot to write bot.use(scenes)
