### ISSUE TITLE
Enter scene for cron

### ISSUE THREAD

**Issue by roviks** [IlyaSemenov/grammy-scenes#15]
Hi! I need to start scene every day at specific time. But to enter scene i need context. How can I start the scene for a user without context?

**Comment by IlyaSemenov** [comment]
I suppose you can do that with the same method as covered in [Resuming a scene without having chat context](https://github.com/IlyaSemenov/grammy-scenes#resuming-a-scene-without-having-chat-context)

In the example, replace `ctx.scenes.notify` with `ctx.scenes.enter`, that should work.
